highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: https://github.com/epratheeban
author: Pratheeban

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Pratheeban's Resume
name: Pratheeban
email: epratheeban@gmailcom
email_full: mailto:epratheeban@gmail.com
website: https://epratheeban.github.io/vitae/
website_full: 
github: trending
twitter: twitter
tel: +33 (0) 783361655
tel_full: tel:+33783361655
google_maps: 'https://www.google.fr/maps/place/Fondation+Danoise,+7+Boulevard+Jourdan,+75014+Paris/@48.8293536,2.3491942,13z/data=!4m5!3m4!1s0x47e6719f7a9b3c2d:0xb66f7daaeb3ad64!8m2!3d48.8184998!4d2.342459'
address: 7R Boulevard Jourdan
postcode: 75014
city: Paris
country: France
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
